# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:

  quality:

    docker:
      - image: cimg/openjdk:15.0.1

    steps:
      - checkout
      # TODO Detekt
      # TODO Coverage

  build:

    docker:
      - image: circleci/android:api-30

    steps:
      - checkout
      - run:
          name: Verify Database Migrations
          command: ./gradlew verifyDebugDatabaseMigration
      - run:
          name: Build debug
          command: ./gradlew buildDebug
      # TODO build release

  test:

    docker:
      - image: circleci/android:api-30

    steps:
      - checkout
      - run:
          name: Unit Tests
          command: ./gradlew test
      # TODO: Instrumented tests
      # TODO: UI tests

  release:

    docker:
      - image: circleci/android:api-30

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 82:bd:17:83:29:b5:69:8d:8f:25:bb:86:4c:8f:14:a2
      - run:
          name: Update app version
          command: scripts/updateAppVersion.sh && scripts/commitAppVersion.sh
      - run:
          name: Build release
          command: ./gradlew assembleDebug && scripts/createRelease.sh
      # TODO Fastlane to publish to Play Store

workflows:
  main:
    jobs:
      - quality
      - build
      - test
      - release:
          context: Git
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d{1,2}\.\d{1,2}\.\d{1,2}/
