# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:

  release:

    docker:
      - image: circleci/android:api-30

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 82:bd:17:83:29:b5:69:8d:8f:25:bb:86:4c:8f:14:a2
      - run:
          name: Update app version
          command: scripts/updateAppVersion.sh && scripts/commitAppVersion.sh
      - run:
          name: Build release
          command: ./gradlew assembleDebug && scripts/createRelease.sh
      # TODO Fastlane to publish to Play Store
