[versions]
accompanist = "0.24.7-alpha"
androidGradle = "7.2.0"
androidxActivity = "1.4.0"
androidBilling = "5.0.0"
androidxCore = "1.7.0"
androidxEspresso = "3.4.0"
androidxLifecycle = "2.4.1"
androidxTestCore = "1.4.0-rc01"
androidxTestJunit = "1.1.3"
arrow = "1.1.2"
coil = "1.4.0"
compose = "1.2.0-beta03"
constraintLayout = "1.0.0"
crashlytics = "2.8.1"
dataStore = "1.0.0"
detekt = "1.20.0-RC1"
firebase = "30.0.1"
geohash = "1.4.0"
glance = "1.0.0-alpha03"
gsm = "4.3.10"
hiltViewModel = "1.0.0-alpha03"
junit = "4.13.2"
kermit = "1.1.1"
klock = "2.5.1"
koin = "3.2.0"
kotlin = "1.7.0"
kotlinCoroutines = "1.6.0"
kotlinSerialization = "1.3.2"
mockk = "1.12.2"
material3 = "1.0.0-alpha12"
navigation = "2.4.1"
playServices = "19.0.1"
sqlDelight = "1.5.3"
turbine = "0.7.0"
workManager = "2.7.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
gradle-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-gsm = { module = "com.google.gms:google-services", version.ref = "gsm" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-sqlDelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqlDelight" }

ksp-arrow = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrow" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
android-billing = { module = "com.android.billingclient:billing-ktx", version.ref = "androidBilling" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-dataStore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }
androidx-glance = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx-test-junit = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestJunit" }
androidx-workManager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
androidx-workManager-test = { module = "androidx.work:work-testing", version.ref = "workManager" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-optics = { module = "io.arrow-kt:arrow-optics", version.ref = "arrow" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayout"}
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-uiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
geohash = { module = "ch.hsr:geohash", version.ref = "geohash" }
junit = { module = "junit:junit", version.ref = "junit" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
klock = { module = "com.soywiz.korlibs.klock:klock", version.ref = "klock" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-android-workManager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinCoroutines" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
playServices-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServices" }
sqlDelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-coroutines = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-sqlite = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
base = [ "arrow-core", "arrow-optics", "kermit", "koin-core", "kotlin-coroutines" ]
compose = [ "coil-compose", "compose-constraintLayout", "compose-ui", "compose-uiToolingPreview", "koin-android-compose", "material3" ]
test-android = [ "androidx-test-core", "androidx-test-junit", "androidx-test-espresso", "koin-test", "koin-test-junit4", "mockk-android" ]
test-kotlin = [ "kotlin-coroutines-test", "kotlin-test-junit", "mockk", "turbine" ]

