name: Build

on: [push]

jobs:

  Database:

    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Verify Database Migrations
        run: ./gradlew verifyDebugDatabaseMigration

  Debug:

    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Create google-services json
        run: |
          echo '${{ secrets.FIREBASE_SECRET }}' > ${GITHUB_WORKSPACE}/app/google-services.json

      - name: Build Debug version
        run: ./gradlew buildDebug

  # TODO Build Release
