name: Deploy to Play Store

on:
  push:
    branches:
      - main

jobs:

  Deploy:
    name: Deplay to Play Store

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Assemble Debug Apk
        run: ./gradlew assembleDebug
        env:
          APP_VERSION: ${{ github.run_number }}

      - name: Assemble Bundle Release
        run: ./gradlew bundleRelease
        env:
          APP_VERSION: ${{ github.run_number }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     name: ${{ github.run_number }}
      #     tag_name: ${{ github.run_nunner }}
      #     files: |
      #       app/build/outputs/apk/debug/*
      #       app/build/outputs/bundle/release/*.aab
      #       app/build/outputs/mapping/release/mapping.txt

      - name: Upload Relase archive
        uses: actions/upload-artifact@v3
        with:
          name: archive
          path: |
            app/build/outputs/apk/debug/*
            app/build/outputs/bundle/release/*.aab
            app/build/outputs/mapping/release/mapping.txt

      - name: Upload Android Release to Play Store - Internal track
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          track: alpha
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          packageName: studio.forface.shuttle
          releaseFiles: app/build/outputs/bundle/release/*.aab
          mappingFile: app/build/outputs/mapping/release/mapping.txt
